# Generated by Django 5.1.6 on 2025-09-22 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_created_at_alter_variation_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylog',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='stock',
        ),
        migrations.CreateModel(
            name='VariationCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('color_variation', models.ForeignKey(blank=True, limit_choices_to={'variation_category': 'color'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_combinations', to='store.variation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_combinations', to='store.product')),
                ('size_variation', models.ForeignKey(blank=True, limit_choices_to={'variation_category': 'size'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_combinations', to='store.variation')),
            ],
            options={
                'unique_together': {('product', 'size_variation', 'color_variation')},
            },
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='variation_combination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.variationcombination'),
        ),
    ]
