# Generated by Django 5.1.6 on 2025-09-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_inventorylog_variation_remove_variation_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
    ]
