# Generated by Django 5.1.6 on 2025-09-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_variation_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('variation_category', 'variation_value')},
        ),
    ]
