# Generated by Django 5.1.3 on 2025-09-11 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_remove_order_expected_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathaoCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('merchant_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_status', models.CharField(default='Pending', max_length=50)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pathao_courier', to='orders.order')),
            ],
            options={
                'verbose_name': 'Pathao Courier',
                'verbose_name_plural': 'Pathao Couriers',
            },
        ),
    ]
