# Generated by Django 5.1.3 on 2025-09-11 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathaoCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(unique=True)),
                ('city_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pathao City',
                'verbose_name_plural': 'Pathao Cities',
            },
        ),
        migrations.CreateModel(
            name='PathaoZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(unique=True)),
                ('zone_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='parcel.pathaocity')),
            ],
            options={
                'verbose_name': 'Pathao Zone',
                'verbose_name_plural': 'Pathao Zones',
            },
        ),
        migrations.CreateModel(
            name='PathaoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.IntegerField(unique=True)),
                ('area_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='parcel.pathaozone')),
            ],
            options={
                'verbose_name': 'Pathao Area',
                'verbose_name_plural': 'Pathao Areas',
            },
        ),
    ]
