# Generated by Django 5.1.3 on 2024-11-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='total_amount',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(),
        ),
    ]
