# Generated by Django 5.1.3 on 2024-11-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderproduct_total_amount_alter_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='size',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('SSLcommerz', 'SSLcommerz')], max_length=50),
        ),
    ]
