# Generated by Django 5.1.3 on 2024-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderproduct_color_alter_orderproduct_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('SSLcommerz', 'SSLcommerz')], default='Cash on Delivery', max_length=50),
        ),
    ]
