# Generated by Django 5.1.3 on 2025-09-11 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_expected_delivery_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expected_delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
    ]
