# Generated by Django 5.1.3 on 2025-09-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_pathao_area_id_order_pathao_city_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
